Copy code
name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install dependencies
        id: InstallDependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
        continue-on-error: true
      
      - name: Run tests
        id: RunTests
        run: ./vendor/bin/phpunit
        continue-on-error: true
      
      - name: Install lftp
        id: InstallFtp
        run: sudo apt-get install -y lftp
        continue-on-error: true
      
      - name: Deploy to FTP
        id: DeployToFtp
        run: |
          lftp -c "open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }} && mirror -R ./path/to/deploy /remote/path"
        continue-on-error: true
      
      - name: Handle deployment errors
        if: ${{ steps.InstallDependencies.outcome != 'success' || steps.RunTests.outcome != 'success' || steps.InstallFtp.outcome != 'success' || steps.DeployToFtp.outcome != 'success' }}
        run: |
          echo "Pipeline failed at step: ${{ job.steps[steps.DeployToFtp.id].name }}"
          exit 1